# sudo: required
# language: node_js
# node_js:
# - node
# after_success:
# - chmod +x deploy.sh
# - "./deploy.sh"


---
sudo: required
dist: trusty
language: node_js
node_js:
  # LTS version
  - "8.10"
notifications:
  email:
    on_success: change # only if status change from fail to success
    on_failure: always # if there is a fail
    recipients:
      - midhun@zeefasys.com
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm i -g react-deploy-cli
  - npm run build #use your build script

after_success:
- chmod +x deploy.sh
- "./deploy.sh"